### ISSUE TITLE
新規投稿

### ISSUE THREAD

**Issue by tamurayk** [tamurayk/laravel-photo-sharing-app#2]
### URL

- GET /create
- POST /create

### TODO

- [x] 事前調査
    - [x] 画像アップロード方法の基礎を把握
        - formタグ enctype="multipart/form-data"
        - inputタグ type属性 file
    - [x] Laravel での画像アップロード方法を把握
    - [x] `Laravel Collective` (Form ファサード) 使うかどうか決める
        - 使う場合
            `$ composer require "laravelcollective/html":"6.*"`
        - (決) 使わない
            - 逆に blade が読みづらくなりそう
            - バージョン依存するので、バージョンアップの際に From ファサードを使うのをやめた、という情報もあった
    - [x] VerifyCsrfToken ミドルウェア
        - webミドルウェアグループに含まれている、VerifyCsrfToken ミドルウェアが、リクエスト中のトークンとセッションに保存されているトークンが一致するか確認

- [x] URL決める
    - `GET /create` vs `GET /{ユーザー名}/post/create`
        - RestAPI のURLの場合は後者だが、今回(Laravelのview+controller)の場合はどうするか
        - (決) 前者で
    - `POST /create` vs `POST /{ユーザー名}/post`

- [-] 画像アップロード先ディレクトリ作成 // storeメソッドで保存すれば、ディレクトリ作ってくれそうなので、一旦パス
    - ディレクトリ
        - storage/app/public/{user_id}/posts
    - ファイル名
        - {uuid}.jpeg
        - {uuid}.png

- [x] posts テーブル追加
    - [x] migration
    - [x] model 追加

- [x] GET /create
    - [x] routing
        - [x] ログイン済みの場合のみアクセス可能に
    - [x] controller 追加
        - User/Post/PostCreateController.php
            - `return view('user.post.create')` するだけ
    - [x] view 作成
        - formタグ enctype="multipart/form-data"
        - inputタグ type属性 file
        - `{{ csrf_field }}`
            - 以下を出力
                - `<input type="hidden" name="_token" value="tyKtcrH2KscjxVAsxb3KHXG5ppZ8te6PA6SJY8df">`

- [x] POST /create
    - [x] routing
    - [x] controller 追加
        - User/Post/PostStoreController.php
    - [x] formRequest 追加
    - [x] useCase 追加
        - [x] ImageStoreUseCase
            - store メソッドで保存
            - `$path = $request->file('image')->store(sprint_f('public/posts/%s', $user_id));`
                - `storeAsメソッドを使用` で任意のファイル名を指定できるので、uuid にする
            - `$post->image_path = basename($path);`
        - [x] PostStoreUseCase

### useCase

- [x] app/Http/UseCases/User/Post/ImageStore.php
    - in
        - リクエストデータのimage
    - out
        - 保存した画像のbasename

- [x] app/Http/UseCases/User/Post/PostStore.php
     - in
        - int $userID
        - array $data
    - out
        - $postEloquent->save() の結果

## TODO ひとまず icebox に入れて他を実装する

- [x] ファイルサイズの制限
- [x] 画像アップロード時にクロップ
