### ISSUE TITLE
投稿一覧 (自分/他人 共通)

### ISSUE THREAD

**Issue by tamurayk** [tamurayk/laravel-photo-sharing-app#8]
## URL

- GET /{ユーザー名}

## route/action

- route
    - post.index
- action
    - index

## 機能

- [x] URLで指定された `{ユーザー名}` の投稿一覧をリスト表示
    - `{ユーザー名}` = `user_profiles.name`
- [x] ページャー

## 処理内容

- **認証なし**
- ~~userId 取得~~ UserProfiles Entity 取得
    - `select * from user_profiles where name = {ユーザー名};`
- `LengthAwarePaginator` 取得

## TODO

- [x] routing
- [x] Controller
- [x] blade

- [x] user_profiles テーブル追加
    - [x] model 追加

- [x] useCase
    - PostIndexUseCase
        - args
            - string userName
            - array $paginatorParam = []
        - return
            - LengthAwarePaginator
        - note
            - userName から UserProfiles エンティティ を取得
            - 取得できない場合は404
            - userId 取得
                - UserProfiles.user_id

- [x] controller実装

- [x] blade
    - [x] user_profile にデータを作る (ひとまず phpmyadmin で)
    - [x] 一覧表示
    - [x] ページャー
        - `{{ $paginator->links() }}`
    - [x] ~~一覧のデザインをブラッシュアップ~~ ice box

## note: 画像表示

- `public/storage` から `storage/app/public` へシンボリックリンク
    - `php artisan storage:link`
- **Nginxコンテナに、`./src/storage/app/public:/srv/public/storage` をマウント** //ハマりどころ
- blade: `<img src="{{ asset('storage/ユーザーID/posts/' . $post->image) }}">`

## 次のタスク

- ユーザー登録時に user_profiles を必須項目にする
